DROP DATABASE IF EXISTS calculator;
DROP USER IF EXISTS `calculator_user`@`%`;
CREATE DATABASE IF NOT EXISTS calculator CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `calculator_user`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `calculator`.* TO `calculator_user`@`%`;
FLUSH PRIVILEGES;